version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env    # <-- El .env tendria que estar en la carpeta donde esta docker-compose yml pero aqui esta en back
    environment:
      - MONGO_URI=${MONGO_URI}  # <-- Usará el valor del .env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Nginx usa el puerto 80
    depends_on:
      - backend

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin   # <-- Cambiar si quieres
      MONGO_INITDB_ROOT_PASSWORD: Panchito1234 # <-- Cambiar en producción!
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: