name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # Sistema operativo
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      
      - name: Install dependencies
        working-directory: frontend  
        run: npm install

     
      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build
          mv build ../public  # Mueve la carpeta build a raíz como "public"


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token automático
          publish_dir: ./public  # Carpeta a publicar